name: Code check
on: [push]
jobs:
  code_checks:
    name: Linters & Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.0
      - name: Install dependencies
        run: |
          make install-requirements
          make install-pre-commit
      - name: Run linters and tests
        run: make pre-commit